# Alto Central - Site Configuration
# This file is shared between frontend and backend
# Add new sites here to have them appear on the map and be available to the system

# Default map settings
map:
  center:
    latitude: 13.7563
    longitude: 100.5018
  zoom: 6

# List of all sites
sites:
  - site_id: mbk
    site_name: MBK Center
    site_code: MBK
    latitude: 13.7446291
    longitude: 100.5275835
    timezone: Asia/Bangkok
    hvac_type: water
    building_type: retail
    database:
      timescaledb:
        host: 10.144.87.224
        port: 5432
        database: postgres
        user: postgres
        password: Magicalmint@636
      mongodb:
        uri: mongodb://10.144.87.224:27017//

  - site_id: cp9
    site_name: Central Rama 9
    site_code: CP9
    latitude: 13.7585954
    longitude: 100.5636025
    timezone: Asia/Bangkok
    hvac_type: water
    building_type: retail
    database:
      timescaledb:
        host: 10.144.65.134
        port: 5432
        database: postgres
        user: postgres
        password: Magicalmint@636
      mongodb:
        uri: mongodb://10.144.65.134:27017//

  - site_id: kspo
    site_name: Bank of Ayudhya (Krungsri) - Phloen Chit Office
    site_code: KSPO
    latitude: 13.7430946
    longitude: 100.5444255
    timezone: Asia/Bangkok
    hvac_type: water
    building_type: office
    design_capacity_rt: 3000
    database:
      timescaledb:
        host: 10.144.168.147
        port: 5433
        database: postgres
        user: postgres
        password: Magicalmint@636
      supabase:
        url: http://10.144.168.147:8000
        anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      mongodb:
        uri: mongodb://10.144.168.147:27017//

  - site_id: bla
    site_name: Bangkok Life Assurance Public Company Limited
    site_code: BLA
    latitude: 13.8256467
    longitude: 100.5276992
    timezone: Asia/Bangkok
    hvac_type: water
    building_type: office
    database:
      timescaledb:
        host: 10.144.140.149
        port: 5433
        database: postgres
        user: postgres
        password: Magicalmint@636
      supabase:
        url: http://10.144.140.149:8000
        anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      mongodb:
        uri: mongodb://10.144.140.149:27017//

  - site_id: densobpk
    site_name: Denso (Thailand) Co., Ltd. (WGR)
    site_code: DENSOBPK
    latitude: 13.599091
    longitude: 100.6725143
    timezone: Asia/Bangkok
    hvac_type: water
    building_type: office
    database:
      timescaledb:
        host: 10.144.27.81
        port: 5432
        database: postgres
        user: postgres
        password: Magicalmint@636
      mongodb:
        uri: mongodb://10.144.27.81:27017//

  - site_id: uob
    site_name: UOB Plaza Bangkok Building
    site_code: UOB
    latitude: 13.7296
    longitude: 100.5678861
    timezone: Asia/Bangkok
    hvac_type: water
    building_type: office
    database:
      timescaledb:
        host: 10.144.40.1
        port: 5433
        database: postgres
        user: postgres
        password: Magicalmint@636
      supabase:
        url: http://10.144.40.1:8000
        anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      mongodb:
        uri: mongodb://10.144.40.1:27017//